### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by gabrielguarido** [raimiyashiro/coffeehub#2]
Hi there 👋 

Here are some fixes that I believe would solve your problem with this API.
Click [here](https://github.com/raimiyashiro/coffeehub/pull/1) to see the PR, already merged btw.

---

Changes:
- [x] Added `hibernate validator` dependency to the `pom.xml`.
- [x] Implemented `Log4J` lib to log request's activity.
- [x] Enabled Logging Level `INFO` for the application.
- [x] Implemented `javax validation` for JPA classes.
- [x] Changed the `ID` generation type to `AUTO`
- [x] Modified the `@Repository` classes to extend `JpaRepository` instead of `CrudRepository`.
- [x] Removed unnecessary constructor methods.
- [x] Cleaned `@Service` methods.
- [x] Cleaned `@Controller` methods - Catching and logging exceptions.

---

I believe the payloads for creating new registers should be something like this:
- Creating a new `Note`:
```
{
   "text": "Example",
   "book": {
      "id": 1
   }
}
```

- Creating a new `Book`:
```
{
   "title": "Example"
}
```

FYI: The `ID` will be created automatically, so there's no need to specify them on your payload.

**Comment by raimiyashiro** [comment]
Hey, good fella!

I got this problem when trying to create a new book:

`Invalid property 'id' of bean class [com.coffeehub.models.Book]: Getter for property 'id' threw exception; nested exception is java.lang.reflect.InvocationTargetException`

Can u help me further?

**Comment by raimiyashiro** [comment]
Apparently, the problem is solved when I send a symbolic "id" field in the request body, which value will be replaced automatically. However, when trying to create a note, I have the following problem:

`c.coffeehub.controllers.NoteController   : Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction`

**Comment by gabrielguarido** [comment]
Sure, can I see your payload?

**Comment by gabrielguarido** [comment]
Ended up that when I first reviewed your code, I changed the id type from long to Long, but I forgot to change the attribute type on getter and setter methods. That solves the NullPointerException issue. My bad 😞

Click [here](https://github.com/raimiyashiro/coffeehub/pull/3) to see the PR with the code fixes.

**Comment by raimiyashiro** [comment]
That's fine!
